server:
  port: 8081  servlet:    context-path: /sales-ms
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:    console:      enabled: true      path: /h2-console#spring:#  datasource:
#    url: jdbc:oracle:thin:@aafma93dv6culb.cznpwujljkql.us-east-2.rds.amazonaws.com:1521:orcl
#    username: jeanov#    password: jeanov123
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:      ddl-auto: create
