server:
  port: 8081  servlet:    context-path: /sales-ms
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:    console:      enabled: true      path: /h2-console  jpa:    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:      ddl-auto: create
