server:
  port: 8081  servlet:    context-path: /sales-ms
spring:  datasource:    url: jdbc:oracle:thin:@sales-db.cznpwujljkql.us-east-2.rds.amazonaws.com:1521:orcl
    username: admin
    password: admin123  jpa:    generate-ddl: true
    hibernate:
      ddl-auto: create
